#!/usr/bin/env python

import sys
import re
msg = open(sys.argv[1], "r").read()

if not re.match(r"\[#[0-9]{1,}\]\s", msg):
	print("Commit reverted")
	print("Incorrect commit message pattern")
	print("Commit message must match pattern: [#number] message")
	sys.exit(-1)