# This is a basic workflow to help you get started with Actions

name: Deploy prod

# Controls when the workflow will run
on:
  workflow_run:
    workflows:
      - Kotlin package
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Deploy to prod env
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE }} mod@206.189.36.39
          cd ~/server/prod/scripts/ || return
          sh ./build.sh
